import type { AssetMetadata } from "./types";

export const ASSET_CATALOG: readonly AssetMetadata[] = [
  {
    assetId: "sofa",
    name: "Sofa",
    category: "living-room",
    modelPath: "/assets/furniture/sofa.glb",
    dimensions: { width: 2.2, height: 0.979, depth: 0.92 },
    footprintOffset: { x: -2.6, z: 0 },
    allowRotation: true,
    allowScaling: true,
  },
  {
    assetId: "racing_gaming_chair",
    name: "Gaming chair",
    category: "furniture",
    modelPath: "/assets/furniture/racing_gaming_chair.glb",
    dimensions: { width: 0.7, height: 1.275, depth: 0.77 },
    footprintOffset: { x: -0.01, z: 0.04 },
    allowRotation: true,
    allowScaling: true,
  },
  {
    assetId: "modern_table",
    name: "Modern table",
    category: "furniture",
    modelPath: "/assets/furniture/modern_table.glb",
    dimensions: { width: 1.828, height: 0.75, depth: 0.928 },
    footprintOffset: { x: 0, z: 0 },
    allowRotation: true,
    allowScaling: true,
  },
  {
    assetId: "bed",
    name: "Bed",
    category: "bedroom",
    modelPath: "/assets/furniture/bed.glb",
    dimensions: { width: 1.75, height: 1.295, depth: 2.168 },
    footprintOffset: { x: 0, z: 0.01 },
    allowRotation: true,
    allowScaling: true,
  },
  {
    assetId: "modern_closet",
    name: "Closet",
    category: "bedroom",
    modelPath: "/assets/furniture/modern_closet.glb",
    dimensions: { width: 1.808, height: 2, depth: 0.633 },
    footprintOffset: { x: 0, z: -0.01 },
    allowRotation: true,
    allowScaling: false,
  },
  {
    assetId: "cabinet",
    name: "Cabinet",
    category: "furniture",
    modelPath: "/assets/furniture/cabinet.glb",
    dimensions: { width: 1.46, height: 0.955, depth: 0.518 },
    footprintOffset: { x: 0, z: 0.01 },
    allowRotation: true,
    allowScaling: true,
  },
  {
    assetId: "fridge",
    name: "Fridge",
    category: "kitchen",
    modelPath: "/assets/furniture/fridge.glb",
    dimensions: { width: 0.9, height: 1.78, depth: 0.895 },
    footprintOffset: { x: 0, z: 0.03 },
    allowRotation: true,
    allowScaling: false,
  },
  {
    assetId: "modern_tv",
    name: "TV",
    category: "living-room",
    modelPath: "/assets/furniture/modern_tv.glb",
    dimensions: { width: 1.445, height: 1.36, depth: 0.252 },
    footprintOffset: { x: 0, z: 0 },
    allowRotation: true,
    allowScaling: false,
  },
  {
    assetId: "round_clock",
    name: "Clock",
    category: "decoration",
    modelPath: "/assets/furniture/round_clock.glb",
    dimensions: { width: 0.3, height: 0.3, depth: 0.065 },
    footprintOffset: { x: 0, z: 0.01 },
    allowRotation: true,
    allowScaling: false,
  },
  {
    assetId: "test_crate",
    name: "Test crate",
    category: "decoration",
    modelPath: "/assets/decoration/test_crate.glb",
    dimensions: { width: 0.5, height: 0.5, depth: 0.5 },
    footprintOffset: { x: -0.25, z: -0.25 },
    allowRotation: true,
    allowScaling: false,
  },
];
